### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by eduardstefan2006** [bureus/MMM-Nightscout#2]
Can you make the module to show the last 3 or 5 blood glucoses? .. to give us an idea of the trend.

**Comment by bureus** [comment]
Hi, absolutely! Trend is currently calculated and shows up below the glucose value. You see the diff between the latest value and the value before. I can ofc add a list of x number of values below if you also would like that.  How do you want it? Is a list below the latest glucose value OK? 

BR

**Comment by eduardstefan2006** [comment]
Hello, in my dream :), this app  should look like in the picture ... in my dream. 

![IMG_20190401_133144](https://user-images.githubusercontent.com/14857269/55341147-cc4aaf00-54ae-11e9-8c72-c8144d6c9a0b.jpg)

**Comment by bureus** [comment]
Thanks for the info, im working on something similar :) hope to have something ready by end of this week.

**Comment by bureus** [comment]
@eduardstefan2006 : Released chart in the latest update. Please read readme and also ensure you do a `npm install` after git pull.

**Comment by eduardstefan2006** [comment]
God job man. This is like my dream :)
