### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by infallibleapex** [bureus/MMM-Nightscout#3]
Can we have the website name show above the arrow? I know you are already scraping for the number and trend arrow.

**Comment by bureus** [comment]
Hi,

Thanks for reaching out. That should not be a problem, will include in next release as the header of the module, which will come soon but currently working on implementing a graph so even if it is a small fix it could take a day or two.

Stay tune :)

**Comment by bureus** [comment]
@infallibleapex : Added the website name from server config in latest commit, so please get latest and ensure you run npm install after pull.
