### ISSUE TITLE
wrong position as soon rendering graph

### ISSUE THREAD

**Issue by CaptainBalou** [bureus/MMM-Nightscout#4]
Hello bureus,

thanks for this very helpful module. It works like a sharm while just displaying the value and trend (renderChart: false). It is showing up in the bottom_left position as configured. As soon as I use the chart the position is not correct anymore. It then uses a some kind of random position on the top left.

Can I provide you with some debugs to get a clearer picture of this issue?

Regards
Marco

**Comment by bureus** [comment]
Hi @CaptainBalou, sorry for late reply, will look into this as soon as possible and report back to you :)

**Comment by bureus** [comment]
Could you post a print screen if possible of how it looks?

**Comment by bureus** [comment]
@CaptainBalou should have been fixed now! I did set the height of the chart which was not needed, so thats why it renders over the whole height and therefor ended up top. So please verify by updating the module:

Run git pull inside ../modules/MMM-Nightscout/ folder.
Run npm install inside ../modules/MMM-Nightscout/ folder
