### ISSUE TITLE
Entire module freezes

### ISSUE THREAD

**Issue by Zzeall** [bureus/MMM-Nightscout#5]
The module works and updates for a couple of minutes, sometimes for hours but then freezes. It stops updating entirely, and the only way to fix it is to restart the PI. I've looked at the nightscout website to see if it's freezing there but it not. It's done this since install.

**Comment by bureus** [comment]
@Zzeall: Okej, do you have any logs? I might have seen similar issues, but it has happened after sensor change. I will add some more error handling and also look into if I found something in my logs. But appreciated if you can try to find anything valuable entries within your logs and share it here.

**Comment by bureus** [comment]
@Zzeall : I might have found something within the code. So i have just released a patch to solve it hopefully. So please update your module and let me know if it did not solve connection problems.
