### ISSUE TITLE
Does this work with Nightscout on Heroku ?

### ISSUE THREAD

**Issue by xerv23** [bureus/MMM-Nightscout#6]
Hi bureus,

i am trying to get your modul to work on my MM. But MM always fails on startup because the config is  not working. Error in the line "colorEnabled: true " or above. So i wonder if the modul does not work with Nightscout hostet on Heroku instead of Azzure.  i am pretty sure i got my config right. i also deleted all moduls but the Nighscout. Same result.

Thanks in advance.

**Comment by majik655** [comment]
I got this working but what I found during the process of putting in your module in your config is it is missing commas at the end of the config lines...
`                {
                        module: "MMM-Nightscout",
                        position: "top_left",
                        config: {
                                debug: false, //Optional: set to true if you want debug logs
                                baseUrl: 'https://YOURSITENAMEHERE.herokuapp.com', //Required: Base url to your Nightscout webapplication. $
                                colorEnabled: true, //Optional: set to true if you want to get colorful bs values. Default is false.
                                chartWidth: 350,  //Optional: set chart width in px. Default is 350px.
                                chartHours: 4, //Optional: number of hours that chart tracks. Default is 4.
                                renderChart: true,  //Optional: set to false if you dont want to get a chart. Default is true.
                                extendedHeader: false, //Option: set to false if you want to hide server title and last glucose value.
                        }
                },
`
Notice the comma at the end of everything such as true,   end of every line put a comma

The instructions are missing a command on a few of them.

**Comment by bureus** [comment]
@majik655 thanks alot for helping! I will update readme with your comments tomorrow. Sorry for late reply due to vacation. 

BR
