### ISSUE TITLE
Possible to use API_SECRET protected baseUrl

### ISSUE THREAD

**Issue by GoudekettingRM** [bureus/MMM-Nightscout#8]
Hi,

I actually have a nightscout website that is protected using an API_SECRET env variable and I would like to keep it like that. However, hooking up my glucose monitoring to my magic mirror also seems like a nice concept. Do you know if it would be possible to do something like that or do you have support for it planned?

Thanks a bunch!

**Comment by GoudekettingRM** [comment]
Alright, I've been playing around with it a little and it is possible. I have a few changes that I made in my local clone of your repo. I can give you some pointers if you like to add it.

The api of the nightscout server requests a header called `API-SECRET` (note the dash rather than an underscore). And then you need to add the api key as a SHA1 formatted string. So they recommend running it through this: http://www.sha1-online.com/

I'm not sure if you can build that into the code, but adding an option config setting that is apiSecret (which should be the SHA1 api secret) and then just conditionally adding the header to the `getServerConfig` and `getGlucoseData` if the setting for the apiSecret is set does the trick for me.

**Comment by fabkai** [comment]
Hi @bureus @GoudekettingRM,
I also have a nightscout website that is protected using an API_SECRET env variable. Would it be possible to take @GoudekettingRM suggestion into the module - that would be really great?
As I understand it, it should also be possible to authenticate with a token via the REST API: e.g. https://base-url:port/api/v1/entries.json?token=nightscout-token. Maybe that's another alternative to the hashed API secret.

**Comment by GoudekettingRM** [comment]
@fabkai I have a fork of the project here with a commit that adds a API secret as an option. You should be able to install it instead of this one. Just make sure to convert your API secret to sha1. https://github.com/GoudekettingRM/MMM-Nightscout

**Comment by fabkai** [comment]
@GoudekettingRM Thanks for the quick answer - it works without problems :-)

**Comment by GoudekettingRM** [comment]
@fabkai You're welcome, glad I could help(:

**Comment by GoudekettingRM** [comment]
@daniel2887 just confirming; did you SHA1 encode your apiSecret in your config?
