### ISSUE TITLE
MMM-Nightscout don't work with Google Cloud

### ISSUE THREAD

**Issue by Sorelie** [bureus/MMM-Nightscout#9]
I only see the Nightscout logo. Nothing else. Try different url's (with and without tokens). -.-

**Comment by tossegus** [comment]
Is your data public? I haven't seen any option - currently - to allow using tokens. I've been working on adding tokens, but haven't been able to push a branch for review yet.

**Comment by bureus** [comment]
Tokens are supported now, sorry for late cancelations.
